Starting Execution
07/07/2018 15:06:46
INFO:root:Tensorflow 1.8.0
INFO:root:Saving to /home/hornberger/MasterarbeitTobias/models/customComp/Alter2
INFO:root:/home/hornberger/MasterarbeitTobias/models/customComp/Alter2 does not exist. Creating folder
INFO:root:loading data from store
INFO:root:Train the DNN Regressor...

(252101, 10) (252101, 2)
(28012, 10) (28012, 2)
we are making progress: 0
eval: {'average_loss': 16669.637, 'loss': 32203438.0, 'global_step': 1000}
we are making progress: 10
eval: {'average_loss': 1262.8005, 'loss': 2439556.5, 'global_step': 11000}
we are making progress: 20
eval: {'average_loss': 968.8385, 'loss': 1871662.4, 'global_step': 21000}
we are making progress: 30
eval: {'average_loss': 768.50964, 'loss': 1484654.6, 'global_step': 31000}
we are making progress: 40
eval: {'average_loss': 516.3546, 'loss': 997525.94, 'global_step': 41000}
we are making progress: 50
eval: {'average_loss': 258.68402, 'loss': 499741.88, 'global_step': 51000}
we are making progress: 60
eval: {'average_loss': 100.34567, 'loss': 193854.0, 'global_step': 61000}
we are making progress: 70
eval: {'average_loss': 44.203533, 'loss': 85395.13, 'global_step': 71000}
we are making progress: 80
eval: {'average_loss': 36.860306, 'loss': 71209.02, 'global_step': 81000}
we are making progress: 90
eval: {'average_loss': 34.439884, 'loss': 66533.1, 'global_step': 91000}
we are making progress: 100
eval: {'average_loss': 32.95549, 'loss': 63665.46, 'global_step': 101000}
we are making progress: 110
eval: {'average_loss': 31.643805, 'loss': 61131.465, 'global_step': 111000}
we are making progress: 120
eval: {'average_loss': 30.376318, 'loss': 58682.86, 'global_step': 121000}
we are making progress: 130
eval: {'average_loss': 29.532852, 'loss': 57053.4, 'global_step': 131000}
we are making progress: 140
eval: {'average_loss': 28.945068, 'loss': 55917.88, 'global_step': 141000}
we are making progress: 150
eval: {'average_loss': 28.473293, 'loss': 55006.473, 'global_step': 151000}
we are making progress: 160
eval: {'average_loss': 28.067389, 'loss': 54222.324, 'global_step': 161000}
we are making progress: 170
eval: {'average_loss': 27.70021, 'loss': 53512.99, 'global_step': 171000}
we are making progress: 180
eval: {'average_loss': 27.364325, 'loss': 52864.098, 'global_step': 181000}
we are making progress: 190
eval: {'average_loss': 27.050327, 'loss': 52257.5, 'global_step': 191000}
we are making progress: 200
eval: {'average_loss': 26.748268, 'loss': 51673.965, 'global_step': 201000}
we are making progress: 210
eval: {'average_loss': 26.461235, 'loss': 51119.457, 'global_step': 211000}
we are making progress: 220
eval: {'average_loss': 26.184526, 'loss': 50584.89, 'global_step': 221000}
we are making progress: 230
eval: {'average_loss': 25.914816, 'loss': 50063.848, 'global_step': 231000}
we are making progress: 240
eval: {'average_loss': 25.657661, 'loss': 49567.066, 'global_step': 241000}
we are making progress: 250
eval: {'average_loss': 25.40809, 'loss': 49084.926, 'global_step': 251000}
we are making progress: 260
eval: {'average_loss': 25.167553, 'loss': 48620.242, 'global_step': 261000}
we are making progress: 270
eval: {'average_loss': 24.932924, 'loss': 48166.97, 'global_step': 271000}
we are making progress: 280
eval: {'average_loss': 24.701338, 'loss': 47719.58, 'global_step': 281000}
we are making progress: 290
eval: {'average_loss': 24.474422, 'loss': 47281.207, 'global_step': 291000}
we are making progress: 300
eval: {'average_loss': 24.25196, 'loss': 46851.445, 'global_step': 301000}
we are making progress: 310
eval: {'average_loss': 24.031912, 'loss': 46426.34, 'global_step': 311000}
we are making progress: 320
eval: {'average_loss': 23.816807, 'loss': 46010.785, 'global_step': 321000}
we are making progress: 330
eval: {'average_loss': 23.60517, 'loss': 45601.93, 'global_step': 331000}
we are making progress: 340
eval: {'average_loss': 23.39709, 'loss': 45199.953, 'global_step': 341000}
we are making progress: 350
eval: {'average_loss': 23.193308, 'loss': 44806.273, 'global_step': 351000}
we are making progress: 360
eval: {'average_loss': 22.9944, 'loss': 44422.008, 'global_step': 361000}
we are making progress: 370
eval: {'average_loss': 22.79776, 'loss': 44042.13, 'global_step': 371000}
we are making progress: 380
eval: {'average_loss': 22.605074, 'loss': 43669.883, 'global_step': 381000}
we are making progress: 390
eval: {'average_loss': 22.415749, 'loss': 43304.133, 'global_step': 391000}
we are making progress: 400
eval: {'average_loss': 22.228777, 'loss': 42942.93, 'global_step': 401000}
we are making progress: 410
eval: {'average_loss': 22.044691, 'loss': 42587.3, 'global_step': 411000}
we are making progress: 420
eval: {'average_loss': 21.863571, 'loss': 42237.406, 'global_step': 421000}
we are making progress: 430
eval: {'average_loss': 21.684338, 'loss': 41891.152, 'global_step': 431000}
we are making progress: 440
eval: {'average_loss': 21.50746, 'loss': 41549.445, 'global_step': 441000}
we are making progress: 450
eval: {'average_loss': 21.331055, 'loss': 41208.656, 'global_step': 451000}
we are making progress: 460
eval: {'average_loss': 21.1591, 'loss': 40876.46, 'global_step': 461000}
we are making progress: 470
eval: {'average_loss': 20.990063, 'loss': 40549.906, 'global_step': 471000}
we are making progress: 480
eval: {'average_loss': 20.823797, 'loss': 40228.703, 'global_step': 481000}
we are making progress: 490
eval: {'average_loss': 20.661283, 'loss': 39914.75, 'global_step': 491000}
Traceback (most recent call last):
  File "DNNRegressor-Example.py", line 380, in <module>
    tf.app.run(main)
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DNNRegressor-Example.py", line 290, in main
    plotTrainDataPandas(featureVals, labelVals, predictions, savePath)
  File "/home/hornberger/Projects/MasterarbeitTobias/implementation/MaUtil.py", line 148, in plotTrainDataPandas
    plt.plot(x, y, 'ro',label='function to predict')
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3347, in plot
    ax = gca()
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/matplotlib/pyplot.py", line 984, in gca
    return gcf().gca(**kwargs)
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/matplotlib/pyplot.py", line 601, in gcf
    return figure()
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 1044, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2020, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
07/07/2018 16:28:37
finished hyperV1
INFO:root:Tensorflow 1.8.0
INFO:root:Saving to /home/hornberger/MasterarbeitTobias/models/customComp/Alter2-custom
INFO:root:/home/hornberger/MasterarbeitTobias/models/customComp/Alter2-custom does not exist. Creating folder
INFO:root:loading data from store
INFO:root:Train the DNN Regressor...

(252101, 10) (252101, 2)
(28012, 10) (28012, 2)
we are making progress: 0
eval: {'average_loss': 4631.83, 'loss': 4474028.5, 'rmse': 68.05755, 'global_step': 1000}
we are making progress: 10
eval: {'average_loss': 497.21848, 'loss': 480278.75, 'rmse': 22.298397, 'global_step': 11000}
we are making progress: 20
eval: {'average_loss': 425.31393, 'loss': 410823.94, 'rmse': 20.62314, 'global_step': 21000}
we are making progress: 30
eval: {'average_loss': 374.38428, 'loss': 361629.38, 'rmse': 19.349012, 'global_step': 31000}
we are making progress: 40
eval: {'average_loss': 321.63626, 'loss': 310678.44, 'rmse': 17.934221, 'global_step': 41000}
we are making progress: 50
eval: {'average_loss': 263.52817, 'loss': 254550.03, 'rmse': 16.233551, 'global_step': 51000}
Traceback (most recent call last):
  File "DNNRegressor-Example.py", line 380, in <module>
    tf.app.run(main)
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DNNRegressor-Example.py", line 282, in main
    debug_predicted = [p['predictions'] for p in debug_pred]
  File "DNNRegressor-Example.py", line 282, in <listcomp>
    debug_predicted = [p['predictions'] for p in debug_pred]
KeyError: 'predictions'
07/07/2018 16:37:09
finished hyperV2
INFO:root:Tensorflow 1.8.0
INFO:root:Saving to /home/hornberger/MasterarbeitTobias/models/customComp/Alter3
INFO:root:/home/hornberger/MasterarbeitTobias/models/customComp/Alter3 does not exist. Creating folder
INFO:root:loading data from store
INFO:root:Train the DNN Regressor...

(252101, 10) (252101, 2)
(28012, 10) (28012, 2)
we are making progress: 0
eval: {'average_loss': 98505.67, 'loss': 95149680.0, 'rmse': 313.85614, 'global_step': 1000}
we are making progress: 10
eval: {'average_loss': 623.4202, 'loss': 602180.94, 'rmse': 24.968384, 'global_step': 11000}
we are making progress: 20
eval: {'average_loss': 295.08878, 'loss': 285035.4, 'rmse': 17.178148, 'global_step': 21000}
we are making progress: 30
eval: {'average_loss': 190.4481, 'loss': 183959.73, 'rmse': 13.800294, 'global_step': 31000}
we are making progress: 40
eval: {'average_loss': 137.80124, 'loss': 133106.48, 'rmse': 11.738877, 'global_step': 41000}
we are making progress: 50
eval: {'average_loss': 107.33774, 'loss': 103680.85, 'rmse': 10.360393, 'global_step': 51000}
Traceback (most recent call last):
  File "DNNRegressor-Example.py", line 380, in <module>
    tf.app.run(main)
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DNNRegressor-Example.py", line 282, in main
    debug_predicted = [p['predictions'] for p in debug_pred]
  File "DNNRegressor-Example.py", line 282, in <listcomp>
    debug_predicted = [p['predictions'] for p in debug_pred]
KeyError: 'predictions'
07/07/2018 16:45:28
finished hyperV3
INFO:root:Tensorflow 1.8.0
INFO:root:Saving to /home/hornberger/MasterarbeitTobias/models/customComp/Alter3-custom
INFO:root:/home/hornberger/MasterarbeitTobias/models/customComp/Alter3-custom does not exist. Creating folder
INFO:root:loading data from store
INFO:root:Train the DNN Regressor...

(252101, 10) (252101, 2)
(28012, 10) (28012, 2)
we are making progress: 0
eval: {'average_loss': 436587.2, 'loss': 421713120.0, 'rmse': 660.74744, 'global_step': 1000}
we are making progress: 10
eval: {'average_loss': 962.2621, 'loss': 929478.8, 'rmse': 31.02035, 'global_step': 11000}
we are making progress: 20
eval: {'average_loss': 522.4275, 'loss': 504628.94, 'rmse': 22.856672, 'global_step': 21000}
we are making progress: 30
eval: {'average_loss': 310.67993, 'loss': 300095.38, 'rmse': 17.626116, 'global_step': 31000}
we are making progress: 40
eval: {'average_loss': 212.501, 'loss': 205261.31, 'rmse': 14.5774145, 'global_step': 41000}
we are making progress: 50
eval: {'average_loss': 153.74695, 'loss': 148508.95, 'rmse': 12.399474, 'global_step': 51000}
Traceback (most recent call last):
  File "DNNRegressor-Example.py", line 380, in <module>
    tf.app.run(main)
  File "/home/hornberger/.virtualenvs/gpu-tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DNNRegressor-Example.py", line 282, in main
    debug_predicted = [p['predictions'] for p in debug_pred]
  File "DNNRegressor-Example.py", line 282, in <listcomp>
    debug_predicted = [p['predictions'] for p in debug_pred]
KeyError: 'predictions'
07/07/2018 16:53:51
finished hyperV4
